apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  app-config.json: |
    {
      "apiUrl": "{{ if .Values.global.hostOverwrite }}https://{{ .Values.global.hostOverwrite }}/api{{ else }}/api{{ end }}",
      "production": true
    }